name: Rust

on: [push]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # - name: Clippy
    #   run: cargo clippy --verbose
    - name: Build Release
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@v3
      with:
        name: gray-goo-ubuntu
        path: target/release/app # or path/to/artifact


  build_windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # - name: Clippy
    #   run: cargo clippy --verbose
    - name: Build Release
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@v3
      with:
        name: gray-goo-windows
        path: target/release/app.exe # or path/to/artifact